
package com.mycompany.ilib;

import Clases.Factura;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.views.ContratosCliente;
import com.mycompany.views.ContratosTerminados;
import com.mycompany.views.Estadisticas;
import com.mycompany.views.Recursos;
import com.mycompany.views.Principal;
import com.mycompany.views.RegistroClientes;
import com.mycompany.views.RegistroFacturas;
import com.mycompany.views.Servicios;
import com.mycompany.views.Test;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JPanel;


public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        InitStyles();
        SetDate();
        InitContent();
    }
    
    private void  InitStyles() {
        
        dateText.putClientProperty("FlatLaf.style", "font: 24 $light.font");
        dateText.setForeground(Color.white);
        
        
    }
    
    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "Es");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    
    private void InitContent(){   
    }
    
    public static void ShowJPanel(JPanel p) {
        p.setSize(800, 800);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        app_name = new javax.swing.JLabel();
        btn_prin = new javax.swing.JButton();
        btn_contracts = new javax.swing.JButton();
        btn_clients = new javax.swing.JButton();
        btn_services = new javax.swing.JButton();
        btn_contracts1 = new javax.swing.JButton();
        btn_services2 = new javax.swing.JButton();
        btn_services3 = new javax.swing.JButton();
        btn_services1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(25, 118, 210));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 20));

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("El Perro Guardian");
        menu.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 220, -1));

        btn_prin.setBackground(new java.awt.Color(21, 101, 192));
        btn_prin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_prin.setForeground(new java.awt.Color(255, 255, 255));
        btn_prin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home-outline.png"))); // NOI18N
        btn_prin.setText("Principal");
        btn_prin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_prin.setBorderPainted(false);
        btn_prin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_prin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_prin.setIconTextGap(13);
        btn_prin.setInheritsPopupMenu(true);
        btn_prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prinActionPerformed(evt);
            }
        });
        menu.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 197, 270, 55));

        btn_contracts.setBackground(new java.awt.Color(21, 101, 192));
        btn_contracts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_contracts.setForeground(new java.awt.Color(255, 255, 255));
        btn_contracts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-firmar-un-documento-25.png"))); // NOI18N
        btn_contracts.setText("Contratos");
        btn_contracts.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_contracts.setBorderPainted(false);
        btn_contracts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_contracts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_contracts.setIconTextGap(13);
        btn_contracts.setInheritsPopupMenu(true);
        btn_contracts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contractsActionPerformed(evt);
            }
        });
        menu.add(btn_contracts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 55));

        btn_clients.setBackground(new java.awt.Color(21, 101, 192));
        btn_clients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_clients.setForeground(new java.awt.Color(255, 255, 255));
        btn_clients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account-multiple.png"))); // NOI18N
        btn_clients.setText("Clientes");
        btn_clients.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_clients.setBorderPainted(false);
        btn_clients.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_clients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_clients.setIconTextGap(13);
        btn_clients.setInheritsPopupMenu(true);
        btn_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientsActionPerformed(evt);
            }
        });
        menu.add(btn_clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 60));

        btn_services.setBackground(new java.awt.Color(21, 101, 192));
        btn_services.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_services.setForeground(new java.awt.Color(255, 255, 255));
        btn_services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seguridadpng.png"))); // NOI18N
        btn_services.setText("Servicios");
        btn_services.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_services.setBorderPainted(false);
        btn_services.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_services.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_services.setIconTextGap(13);
        btn_services.setInheritsPopupMenu(true);
        btn_services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_servicesActionPerformed(evt);
            }
        });
        menu.add(btn_services, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 270, 60));

        btn_contracts1.setBackground(new java.awt.Color(21, 101, 192));
        btn_contracts1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_contracts1.setForeground(new java.awt.Color(255, 255, 255));
        btn_contracts1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-producto-nuevo-25.png"))); // NOI18N
        btn_contracts1.setText("Contratos Terminados");
        btn_contracts1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_contracts1.setBorderPainted(false);
        btn_contracts1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_contracts1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_contracts1.setIconTextGap(13);
        btn_contracts1.setInheritsPopupMenu(true);
        btn_contracts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contracts1ActionPerformed(evt);
            }
        });
        menu.add(btn_contracts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 55));

        btn_services2.setBackground(new java.awt.Color(21, 101, 192));
        btn_services2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_services2.setForeground(new java.awt.Color(255, 255, 255));
        btn_services2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cadena-de-suministro-27.png"))); // NOI18N
        btn_services2.setText("Recursos");
        btn_services2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_services2.setBorderPainted(false);
        btn_services2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_services2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_services2.setIconTextGap(13);
        btn_services2.setInheritsPopupMenu(true);
        btn_services2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_services2ActionPerformed(evt);
            }
        });
        menu.add(btn_services2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 270, 60));

        btn_services3.setBackground(new java.awt.Color(21, 101, 192));
        btn_services3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_services3.setForeground(new java.awt.Color(255, 255, 255));
        btn_services3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-chart.png"))); // NOI18N
        btn_services3.setText("Estadisticas");
        btn_services3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_services3.setBorderPainted(false);
        btn_services3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_services3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_services3.setIconTextGap(13);
        btn_services3.setInheritsPopupMenu(true);
        btn_services3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_services3ActionPerformed(evt);
            }
        });
        menu.add(btn_services3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 270, 60));

        btn_services1.setBackground(new java.awt.Color(21, 101, 192));
        btn_services1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_services1.setForeground(new java.awt.Color(255, 255, 255));
        btn_services1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar-multiple-check.png"))); // NOI18N
        btn_services1.setText("Facturar");
        btn_services1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_services1.setBorderPainted(false);
        btn_services1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_services1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_services1.setIconTextGap(13);
        btn_services1.setInheritsPopupMenu(true);
        btn_services1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_services1ActionPerformed(evt);
            }
        });
        menu.add(btn_services1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 270, 60));

        header.setBackground(new java.awt.Color(25, 118, 210));
        header.setPreferredSize(new java.awt.Dimension(750, 150));

        dateText.setText("Hoy es {dayname} {day} de {month} de {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(520, 520, 520))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prinActionPerformed
        ShowJPanel(new Principal());
    }//GEN-LAST:event_btn_prinActionPerformed

    private void btn_contractsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contractsActionPerformed
        ShowJPanel(new ContratosCliente(null));
    }//GEN-LAST:event_btn_contractsActionPerformed

    private void btn_servicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_servicesActionPerformed
       ShowJPanel(new Servicios());
    }//GEN-LAST:event_btn_servicesActionPerformed

    private void btn_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientsActionPerformed
        ShowJPanel(new RegistroClientes());
    }//GEN-LAST:event_btn_clientsActionPerformed

    private void btn_services1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_services1ActionPerformed
        ShowJPanel(new RegistroFacturas());
    }//GEN-LAST:event_btn_services1ActionPerformed

    private void btn_contracts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contracts1ActionPerformed
        ShowJPanel(new ContratosTerminados());
    }//GEN-LAST:event_btn_contracts1ActionPerformed

    private void btn_services2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_services2ActionPerformed
        ShowJPanel(new Recursos());
    }//GEN-LAST:event_btn_services2ActionPerformed

    private void btn_services3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_services3ActionPerformed
        ShowJPanel(new Estadisticas());
    }//GEN-LAST:event_btn_services3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_clients;
    private javax.swing.JButton btn_contracts;
    private javax.swing.JButton btn_contracts1;
    private javax.swing.JButton btn_prin;
    private javax.swing.JButton btn_services;
    private javax.swing.JButton btn_services1;
    private javax.swing.JButton btn_services2;
    private javax.swing.JButton btn_services3;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
