/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import Clases.Cliente;
import Clases.Contrato;
import Clases.Factura;
import controlador.ListaContratos;
import controlador.ModeloCliente;
import controlador.ModeloContrato;
import controlador.ModeloFactura;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class RegistroFacturas extends javax.swing.JPanel {
    private ModeloFactura modelo;
    private ModeloCliente modeloCliente;
    private ModeloContrato modeloContrato;
    
    /**
     * Creates new form Principal
     */
    public RegistroFacturas() {
        initComponents();
        modelo = new ModeloFactura();
        modeloCliente = new ModeloCliente();
        modeloContrato = new ModeloContrato();
        
        this.tblfacturas.setModel(modelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jcbMes = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblfacturas = new javax.swing.JTable();
        btnfacturar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title.setText("Facturas");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Identificación del cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mes a facturar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 100, 20));
        add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 40));

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        add(jcbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 40));

        tblfacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblfacturas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 550, 180));

        btnfacturar.setText("Facturar");
        btnfacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturarActionPerformed(evt);
            }
        });
        add(btnfacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnfacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturarActionPerformed
        String identificacion = this.txtIdentificacion.getText();
        int mesSeleccionado = this.jcbMes.getSelectedIndex();
        try {
            Cliente cliente = modeloCliente.obtener(identificacion);
            ListaContratos contratos = modeloContrato.filtrarCliente(identificacion);
            for (int i = 0; i < contratos.total(); i++) {
                Contrato contrato = contratos.obtener(i);
                if (getValidez(contrato.getFechaPrestacion(), contrato.getDuracion()).contains(mesSeleccionado) ) {
                    modelo.agregarFactura(new Factura(cliente.getIdentificacion(), contrato.getValorMensual(),mesSeleccionado, contrato.getCodigo()));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, String.format("El cliente con ID %s no se encuentra registrado", identificacion));
        }
    }//GEN-LAST:event_btnfacturarActionPerformed

    public static List<Integer> getValidez(Date fecha, int duracion){
        Integer [] validez = new Integer [duracion];
        for (int i = 0; i < validez.length; i++) {
            validez[i] = (fecha.getMonth() + i) % 12;
        }
        return Arrays.asList(validez);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnfacturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JTable tblfacturas;
    private javax.swing.JTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables
}
